(function() {var implementors = {};
implementors['hubcaps'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/issues/enum.Sort.html' title='hubcaps::issues::Sort'>Sort</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='hubcaps/rep/struct.Content.html' title='hubcaps::rep::Content'>Content</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/rep/enum.StatusState.html' title='hubcaps::rep::StatusState'>StatusState</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/repositories/enum.Visibility.html' title='hubcaps::repositories::Visibility'>Visibility</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/repositories/enum.Sort.html' title='hubcaps::repositories::Sort'>Sort</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/repositories/enum.Affiliation.html' title='hubcaps::repositories::Affiliation'>Affiliation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/repositories/enum.Type.html' title='hubcaps::repositories::Type'>Type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/repositories/enum.OrgRepoType.html' title='hubcaps::repositories::OrgRepoType'>OrgRepoType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/enum.State.html' title='hubcaps::State'>State</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='hubcaps/enum.SortDirection.html' title='hubcaps::SortDirection'>SortDirection</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
