(function() {var implementors = {};
implementors['hubcaps'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/errors/enum.Error.html' title='hubcaps::errors::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/issues/enum.Filter.html' title='hubcaps::issues::Filter'>Filter</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/issues/enum.Sort.html' title='hubcaps::issues::Sort'>Sort</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/repositories/enum.Visibility.html' title='hubcaps::repositories::Visibility'>Visibility</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/repositories/enum.Sort.html' title='hubcaps::repositories::Sort'>Sort</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/repositories/enum.Affiliation.html' title='hubcaps::repositories::Affiliation'>Affiliation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/repositories/enum.Type.html' title='hubcaps::repositories::Type'>Type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/repositories/enum.OrgRepoType.html' title='hubcaps::repositories::OrgRepoType'>OrgRepoType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/pulls/enum.Sort.html' title='hubcaps::pulls::Sort'>Sort</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/enum.State.html' title='hubcaps::State'>State</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='hubcaps/enum.SortDirection.html' title='hubcaps::SortDirection'>SortDirection</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
